### ISSUE TITLE
Allow pyramiding

### ISSUE THREAD

**Issue by sifdogg** [CryptoMF/frostybot#14]
Hi Team Frosty.  ) I have been playing around with frostybot and I like it very awesome much. Is there any way I could remove the maximum number of contracts limit, I mean buying and selling multiple times i.e. My trading system is configured for multiple entries i.e. pyramiding. 

Awesome bot. Power to the people. 

Thanks in advance

**Comment by CryptoMF** [comment]
Hi there

You can already pyramid using Frostybot.

The size=xxx parameter indicates the total size you want to be long or
short.

So if you are already long 10000 contracts, you can place another order for
20000 contracts. This would actually only place an order for 10000
contracts, leaving you with the 20000 you required.

Hope this helps

**Comment by sifdogg** [comment]
I was thinking of using percentage of balance or multiple. 
In automated mode:
long signal #1: long size =100%. (1x)
long signal #2: long size=100%...(another 1x)
long signal #3: long size=100%...(another 1x)

Signals #2 and #3 always throw an error in the logs, "already long maximum number of contracts, ignore" and don't execute. I'm using it with tradingview which doesn't have any capabilities of tracking how many contracts are in a trade, I was wondering if it's possible to override the limitation that "if already long 10000 and I make another order of 5000, it will not go through as I am already long 10000 which is more".
I hope this clarifies my issue. Thanks for the quick response

**Comment by CryptoMF** [comment]
Thanks for the clarification.

I'll have a chat with the other devs and we'll get back to you on this.

**Comment by sifdogg** [comment]
Much appreciated and hope to be hearing from you soon.

Cheers.

**Comment by CryptoMF** [comment]
Hi there. 

We have implemented your request. Please see [this commit](https://github.com/CryptoMF/frostybot/commit/5d18e41c1f7951bb6b300ab3fb639cdfcf793c5a) for more information.

**To upgrade, run the following commands:**

```
cd /var/www/html/frostybot
cp db/database.db /tmp/database.db.bak
cp log/frostybot.log /tmp/frostybot.log.bak
git pull -f
```

**Comment by sifdogg** [comment]
Great. Much thanks and appreciation to the team and I wish you the best of everything as you traverse the wilderness of the wild west. Cheers.
