### ISSUE TITLE
Command works fine, but error log show something

### ISSUE THREAD

**Issue by buzz2a** [CryptoMF/frostybot#18]
Hello,
I am using the alert for strat as i found in the discord. Notifications for Telegram are doing ok.
But weird 
```
2020-08-06 21:51:48 | NOTICE  | Undefined offset: 1 (lib.output.php:244)
2020-08-06 21:51:48 | NOTICE  | Undefined offset: 2 (lib.output.php:244)
```
appears multiple time

[frosty_log.txt](https://github.com/CryptoMF/frostybot/files/5038187/frosty_log.txt)

**Comment by CryptoMF** [comment]
Fixed with commit https://github.com/CryptoMF/frostybot/commit/f9becf52fb9852f5e08ad39a0fbe1ee5f665663e
