### ISSUE TITLE
Problems with Binance symbols

### ISSUE THREAD

**Issue by JDJoe** [CryptoMF/frostybot#4]
For example, Binance has LTC/USDT, tested combinations, like:
LTC/USDT, LTCUSDT 
But no luck. Same with ADABNB 

```
./frostybot binance:markets symbol=ADABNB
{
    "results": {
        "code": 900,
        "message": "CCXT\\BADSYMBOL: binance does not have market symbol  (\/var\/www\/html\/frostybot\/lib\/ccxt\/php\/base\/Exchange.php:2342)",
        "type": "ERROR"
    },
    "messages": [
        {
            "code": 0,
            "type": "NOTICE",
            "message": "Trying to get property 'symbol' of non-object (lib.exchange.php:144)"
        },
        {
            "code": 0,
            "type": "NOTICE",
            "message": "Trying to get property 'bid' of non-object (lib.exchange.php:145)"
        }
    ]
}
```
So, I thought maybe I get lucky with looking at the position. 

```
./frostybot binance:positions
{
    "results": {
        "code": 900,
        "message": "CCXT\\BADSYMBOL: binance does not have market symbol  (\/var\/www\/html\/frostybot\/lib\/ccxt\/php\/base\/Exchange.php:2342)",
        "type": "ERROR"
    },
    "messages": [
        {
            "code": 0,
            "type": "NOTICE",
            "message": "Trying to get property 'symbol' of non-object (lib.exchange.php:144)"
        },
        {
            "code": 0,
            "type": "NOTICE",
            "message": "Trying to get property 'bid' of non-object (lib.exchange.php:145)"
        }
    ]
}
```
No luck there either. 

Looking at the config, Binance seems to be missing information 
```
binance": {
                "stub": "binance",
                "description": "Binance",
                "exchange": "binance",
                "parameters": {
                    "apiKey": "**********",
                    "secret": "**********"
                },
                "symbolmap": []

```
there is no symbol map and no API URL. 
adding api=https://api.binance.com to config did not work

**Comment by CryptoMF** [comment]
Hi, thanks for the feedback. Unfortunately, we have not added support for Binance at this stage. Only Bitmex, Deribit and FTX are supported as per the readme at https://github.com/CryptoMF/frostybot#supported-exchanges

We will add support for more exchanges if they are requested by enough users, because the code to make frostybot exchange-agnostic is very complex.

**Comment by JDJoe** [comment]
That's sad. I was hoping to get Kraken and Kraken Futures to work too. :)

> the code to make frostybot exchange-agnostic is very complex

I am not a programmer, so pardon my ignorance, but I thought this is what ccxt was built for - to make it easier to connect supported exchanges and not mess around with it in your own code.

**Comment by CryptoMF** [comment]
Yeah you're quite right, CCXT was designed to provide a certain level of abstraction, but many of the exchange response types are different. 

For example, if I place the exact same order on Deribit, FTX and Bitmex, the code to place the order is the same, thanks to CCXT, but the data I get back from each exchange is differently formatted, with different field names etc. For this reason, we have to write normalizers to normalize the outputs from each exchange, and therein lies the complexity.

I've spoken to @barnz and he reckons we should do at least 1 shitcoin exchange, so we decided to go with your Binance request from earlier. We should have support for Binance in the next week or two, depending on how much time I can devote to it. As for Kraken, I think that's gonna be a hard no.

**Comment by CryptoMF** [comment]
After careful review of the Binance API, we have decided that it will not be feasible to incorporate it into FrostyBot at this stage. 
We may revisit this at a later stage, but trying to incorporate it now will involve too much rework in the Frostybot core. For the moment I'll suggest that you try out the FTX exchange. They have quite a few altcoin pairs available to trade.
