### ISSUE TITLE
cancel previous and add new order in one alert message 

### ISSUE THREAD

**Issue by JDJoe** [CryptoMF/frostybot#6]
In the ideal situation, I would like to send this out with just only one TradingView alert message. Can this be done?

Here is what I like to do: 
1. cancel all open orders and enter new market order size=321
1. enter "take profit" order at price=X size=123 

on it's own, this is nothing complicated but how can I combine those into one TV message? 

...and when the direction changes and alert is activated:

1. cancel all open orders and enter new market order
1. enter "take profit" order at price X 

I need to cancel all previous "take profit" orders
Those "take profit" orders are simple limit orders in opposite direction of the market order.

**Comment by CryptoMF** [comment]
Hi JDJoe

Yes this is already possible. In the alert box you can enter multiple commands, as long as each command is on a new line, like this:
```
     <stub>:cancelall symbol=BTCUSD
     <stub>:long size=123 symbol=BTCUSD profittrigger=X
```

The short commands would be the same:

```
     <stub>:cancelall symbol=BTCUSD
     <stub>:short size=123 symbol=BTCUSD profittrigger=X
```   
Hope this answers your question.

**Comment by JDJoe** [comment]
Thanks. This is really good news. 
After I cp my db and log, I had to remove them because it wont let me update. 
Can I just copy my old db back and overwrite the one pulled from the repo?

**Comment by JDJoe** [comment]
` <stub>:short size=100 symbol=BTCUSD profittrigger=X`
This will enter a order that ends with a short position 100.  So, what ever is my long + the short will be executed.  
This is not what I meant. 
I need to place a limit order at price X for only a fraction of the open position. 
Lets say 10% of what ever the long position is. 
Lets say it was 100 long, price moves up. I need a limit sell at X for 10% and if it gets executed, my pos is 90 long after it's executed.

**Comment by CryptoMF** [comment]
> After I cp my db and log, I had to remove them because it wont let me update.

Yeah, copy them back using these commands:
```
cp /tmp/database.db.20200202 db/database.db
cp /tmp/frostybot.log.20200202 log/frostybot.log
```
`I need to place a limit order at price X for only a fraction of the open position.`

The trigger orders don't take inline sizing parameters yet, so try this instead:
```
<stub>:cancelall symbol=BTCUSD
<stub>:long size=123 symbol=BTCUSD
<stub>:close size=10% price=X symbol=BTCUSD
```
Let me know if that works for you

**Comment by JDJoe** [comment]
"close" seems to do the trick but it also give me a warning: 
```
"messages": [
        {
            "code": 800,
            "type": "WARNING",
            "message": "Use of undefined constant limit - assumed 'limit' (this will throw an Error in a future version of PHP) (lib.exchange.php:501)"
        },

```

**Comment by CryptoMF** [comment]
Thanks for reporting that That is a bug. I have pushed a fix for it. Please update again using the same procedure to receive the fix

[Fix commit reference](https://github.com/CryptoMF/frostybot/commit/c4a7857a2b4898ae0a6c65887c69893d808ebd21)
