### ISSUE TITLE
Bitmex Overload Error

### ISSUE THREAD

**Issue by Pusher14** [CryptoMF/frostybot#7]
Can a check be implemented to make sure the position goes through when bitmex gets overloaded?

Positions don't go through at all when this occurs.

`                "message": "CCXT\\EXCHANGENOTAVAILABLE: bitmex {\"error\":{\"message\":\"The system is currently overloaded. Please try again later.\",\"name\":\"HTTPError\"}} (\/var\/www\/html\/frostybot\/lib\/ccxt\/php\/bitmex.php:1269)"
`

**Comment by CryptoMF** [comment]
Thanks for the request. While this is technically possible, there would be no guarantee as to which price you manage to get for the order. This totally defeats the object of automation. I would suggest either planning your trades beforehand with limit orders or ensuring that you have market stops in place using the stoptrigger=xxx parameter. Another option would be to use a better exchange such as FTX or Deribit, that don't trade against their own customers. Once the price is moving on Bitmex, it can be nearly impossible to get an order in, and even if you do the slippage is insane. Also, TradingView has a timeout of 3 seconds on the Webhook, so if you cannot get your order placed within 3 seconds it will kill the webhook request.
