### ISSUE TITLE
Placeholder linked to a TP price, but not triggering trade

### ISSUE THREAD

**Issue by buzz2a** [CryptoMF/frostybot#8]
So let's say i want to enter a position at X, and automatically place a TP at the value of my variable "TP2"
Both of the following alerts trigger the main trade, but are not placing limit sell at TP2
`bitmexdemo:long symbol=BTC/USD size=1000
bitmexdemo:short symbol=BTC/USD size=500 price={{plot("TP2")}}`
or even 
`bitmexdemo:long symbol=BTC/USD size=1000
bitmexdemo:close symbol=BTC/USD size=50% price={{plot("TP2")}}`

Is there something i do wrong ? Or does it has to be placed in 2 different alerts ?
Thanks.

<img width="292" alt="Capture d’écran 2020-04-04 à 19 21 05" src="https://user-images.githubusercontent.com/23646236/78457562-61c4e400-76ab-11ea-90ea-af9311f65063.png">

**Comment by CryptoMF** [comment]
Hi there

Try this  command instead:

bitmexdemo:long symbol=BTC/USD size=500 profittrigger={{plot("TP2")}}

Let me know if this solves your problem

**Comment by buzz2a** [comment]
Thanks for the answer,
Unfortunately no..
This is what i can't achieve : 
-Enter a 1000$ long when signal say so, then immediately place 500$ TP at X
- when signal say short, cancel previous limit order and go short 1000$ with 500$ TP
And the other way around.
This is working...
-1st alert if goshort
`bitmexdemo:short symbol=BTC/USD size=1000
bitmexdemo:long symbol=BTC/USD size=500 profittrigger={{plot("TP4")}}`
-2nd alert if golong
`bitmexdemo:long symbol=BTC/USD size=1000
bitmexdemo:short symbol=BTC/USD size=500 profittrigger={{plot("TP2")}}`

but it's acting really weird like, 1st trade of the test is 500, then it flip for a correct size of 1000 and so on.. but after a few flips, it mess with the orders size and don't cancel limit orders anymore..
There might be a thing that i don't understand.
Thanks for your help

**Comment by CryptoMF** [comment]
`bitmexdemo:cancelall
bitmexdemo:long size=1000
bitmexdemo:close size=500 price={{plot("TP2")}}`

**Comment by buzz2a** [comment]
Doesn't work either...
<img width="747" alt="Capture d’écran 2020-04-05 à 14 58 27" src="https://user-images.githubusercontent.com/23646236/78499115-17953e80-774f-11ea-940c-38c16ae6bc19.png">
<img width="747" alt="Capture d’écran 2020-04-05 à 14 58 27" src="https://user-images.githubusercontent.com/23646236/78499121-1c59f280-774f-11ea-9863-5807bc2673f9.png">

**Comment by CryptoMF** [comment]
Seems like you're putting all 3 commands on 1 line. They need to each be on
separate lines
